version: 2

models:
  - name: stg_customers
    description: "Cleaned customers data for analytics"
    columns:
      - name: customer_id
        description: "primary id"
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null

  # - name: stg_orders
  #   description: "Cleaned orders data for analytics"
  #   columns:
  #     - name: order_id
  #       tests:
  #         - not_null
  #         - unique
  #     - name: customer_id
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_customers')
  #             field: customer_id
  #     - name: total_amount
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "total_amount > 0"

  #     - name: status
  #       tests:
  #         - not_null
  #         - accepted_values:
  #             values: ['completed', 'pending', 'cancelled']

  # - name: stg_products
  #   description: "Cleaned products catalog"
  #   columns:
  #     - name: product_id
  #       tests:
  #         - not_null
  #         - unique
  #     - name: product_name
  #       tests:
  #         - not_null
  #     - name: price
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "price > 0"

  # - name: stg_order_items
  #   description: "Cleaned order items with computed line_total"
  #   columns:
  #     - name: order_item_id
  #       tests:
  #         - not_null
  #         - unique
  #     - name: order_id
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_orders')
  #             field: order_id
  #     - name: product_id
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_products')
  #             field: product_id
  #     - name: quantity
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "quantity > 0"
  #     - name: unit_price
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "unit_price > 0"
  #     - name: line_total
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "line_total >= 0"

  # - name: int_orders_with_items
  #   description: "Denormalized order items joined with orders and products"
  #   columns:
  #     - name: order_item_id
  #       tests:
  #         - not_null
  #         - unique
  #     - name: order_id
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_orders')
  #             field: order_id
  #     - name: product_id
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_products')
  #             field: product_id
  #     - name: line_total
  #       tests:
  #         - not_null
  #         - dbt_utils.expression_is_true:
  #             expression: "line_total >= 0"
